// Declarative schemas for the schema-driven admin CRUD pages.

const STATUS_EDITORIAL = ["draft", "published"];

export const RESOURCES = {
  news: {
    title: "News",
    singular: "News article",
    endpoint: "/api/news",
    columns: [
      { key: "title", label: "Title" },
      { key: "category", label: "Category" },
      { key: "status", label: "Status" },
      { key: "publishedAt", label: "Published", format: "date" },
    ],
    defaults: { status: "draft", featured: false, images: [] },
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", help: "Leave blank to generate from the title." },
      { name: "category", label: "Category", type: "text" },
      { name: "excerpt", label: "Excerpt", type: "textarea" },
      { name: "content", label: "Content (HTML)", type: "richtext" },
      { name: "featuredImage", label: "Cover image", type: "image" },
      {
        name: "images",
        label: "Article photos",
        type: "list",
        itemLabel: "photo",
        help: "Optional. Add as many as you have — they appear as a gallery on the article.",
        itemFields: [
          { name: "url", label: "Photo", type: "image" },
          { name: "caption", label: "Caption", type: "text" },
        ],
      },
      { name: "status", label: "Status", type: "select", options: STATUS_EDITORIAL },
      { name: "featured", label: "Featured", type: "boolean" },
      { name: "publishedAt", label: "Published at", type: "date" },
    ],
  },

  events: {
    title: "Events",
    singular: "Event",
    endpoint: "/api/events",
    columns: [
      { key: "title", label: "Title" },
      { key: "venue", label: "Venue" },
      { key: "status", label: "Status" },
      { key: "eventDate", label: "Date", format: "date" },
    ],
    defaults: { status: "draft", images: [] },
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "eventDate", label: "Event date", type: "date" },
      { name: "startTime", label: "Start time", type: "text" },
      { name: "endTime", label: "End time", type: "text" },
      { name: "venue", label: "Venue", type: "text" },
      { name: "image", label: "Image", type: "image" },
      {
        name: "images",
        label: "Event photos",
        type: "list",
        itemLabel: "photo",
        help: "Optional. Add as many as you have from the event — they appear as a gallery.",
        itemFields: [
          { name: "url", label: "Photo", type: "image" },
          { name: "caption", label: "Caption", type: "text" },
        ],
      },
      { name: "status", label: "Status", type: "select", options: STATUS_EDITORIAL },
    ],
  },

  principalOfficers: {
    title: "Principal Officers",
    singular: "Principal Officer",
    endpoint: "/api/principal-officers",
    columns: [
      { key: "name", label: "Name" },
      { key: "role", label: "Role" },
      { key: "status", label: "Status" },
    ],
    defaults: { status: "published", sortOrder: 0 },
    fields: [
      { name: "name", label: "Full name", type: "text", required: true },
      { name: "role", label: "Role / title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", help: "Leave blank to generate from the name." },
      { name: "summary", label: "Summary", type: "textarea" },
      { name: "bio", label: "Biography", type: "tags", help: "One paragraph per line." },
      { name: "qualifications", label: "Qualifications", type: "tags" },
      { name: "memberships", label: "Professional memberships", type: "tags" },
      { name: "image", label: "Portrait", type: "image" },
      { name: "sortOrder", label: "Display order", type: "number" },
      { name: "status", label: "Status", type: "select", options: STATUS_EDITORIAL },
    ],
  },

  faculties: {
    title: "Faculties & Programmes",
    singular: "Faculty",
    endpoint: "/api/faculties",
    columns: [
      { key: "name", label: "Faculty" },
      { key: "dean", label: "Dean" },
      { key: "status", label: "Status" },
    ],
    defaults: { status: "active", sortOrder: 0 },
    fields: [
      { name: "name", label: "Faculty name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", help: "Leave blank to generate from the name." },
      { name: "tagline", label: "Tagline", type: "text" },
      { name: "summary", label: "Overview", type: "textarea" },
      { name: "dean", label: "Dean", type: "text" },
      { name: "image", label: "Image", type: "image" },
      { name: "programmes", label: "Programmes", type: "tags", help: "One programme per line." },
      { name: "researchAreas", label: "Research areas", type: "tags" },
      { name: "highlights", label: "Highlights", type: "tags" },
      {
        name: "facilities",
        label: "Facilities",
        type: "list",
        itemLabel: "facility",
        help: "Each facility can have its own photo. Shown on the faculty page.",
        itemFields: [
          { name: "name", label: "Facility", type: "text" },
          { name: "image", label: "Photo", type: "image" },
        ],
      },
      { name: "careerOutcomes", label: "Career outcomes", type: "tags" },
      { name: "sortOrder", label: "Display order", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
  },

  gallery: {
    title: "Gallery",
    singular: "Gallery album",
    endpoint: "/api/gallery",
    columns: [
      { key: "name", label: "Album" },
      { key: "status", label: "Status" },
    ],
    defaults: { status: "published", sortOrder: 0, images: [] },
    fields: [
      { name: "name", label: "Album name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", help: "Leave blank to generate from the name." },
      { name: "description", label: "Description", type: "textarea" },
      { name: "coverImage", label: "Cover image", type: "image" },
      {
        name: "images",
        label: "Photos",
        type: "list",
        itemLabel: "photo",
        itemFields: [
          { name: "imageUrl", label: "Image", type: "image" },
          { name: "caption", label: "Caption", type: "text" },
        ],
      },
      { name: "sortOrder", label: "Display order", type: "number" },
      { name: "status", label: "Status", type: "select", options: STATUS_EDITORIAL },
    ],
  },
  departments: {
    title: "Departments",
    singular: "department",
    endpoint: "/api/departments",
    columns: [
      { key: "name", label: "Department" },
      { key: "facultyName", label: "Faculty" },
      { key: "headOfDepartment", label: "Head" },
      { key: "status", label: "Status" },
    ],
    defaults: { status: "active" },
    fields: [
      { name: "name", label: "Department name", type: "text", required: true },
      {
        name: "facultyId",
        label: "Faculty",
        type: "reference",
        endpoint: "/api/faculties",
        required: true,
      },
      { name: "headOfDepartment", label: "Head of department", type: "text" },
      { name: "slug", label: "Slug", type: "text", help: "Leave blank to generate from the name." },
      { name: "description", label: "Description", type: "textarea" },
      { name: "email", label: "Email", type: "text" },
      { name: "phone", label: "Phone", type: "text" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["active", "inactive"],
      },
    ],
  },

  staff: {
    title: "Staff Directory",
    singular: "staff member",
    endpoint: "/api/staff",
    columns: [
      { key: "name", label: "Name" },
      { key: "position", label: "Position" },
      { key: "staffType", label: "Type" },
      { key: "departmentName", label: "Department" },
      { key: "status", label: "Status" },
    ],
    defaults: { status: "active", staffType: "academic" },
    fields: [
      {
        name: "title",
        label: "Title",
        type: "select",
        options: [
          "Prof.",
          "Assoc. Prof.",
          "Dr.",
          "Mr.",
          "Mrs.",
          "Miss",
          "Ms.",
          "Engr.",
          "Arc.",
          "Barr.",
          "Rev.",
          "Chief",
        ],
      },
      { name: "name", label: "Full name", type: "text", required: true },
      { name: "position", label: "Position / title", type: "text" },
      {
        name: "staffType",
        label: "Staff type",
        type: "select",
        options: ["academic", "non-academic"],
        help: "Academic (teaching) staff sit in a faculty and department. Non-academic staff (ICT, bursary, bookshop…) use the Unit field instead.",
      },
      { name: "slug", label: "Slug", type: "text", help: "Leave blank to generate from the name." },
      { name: "profileImage", label: "Photograph", type: "image" },
      { name: "facultyId", label: "Faculty", type: "reference", endpoint: "/api/faculties" },
      {
        name: "departmentId",
        label: "Department",
        type: "reference",
        endpoint: "/api/departments",
        // Names repeat across faculties, so show which faculty it sits in.
        labelKeys: ["name", "facultyName"],
      },
      {
        name: "unit",
        label: "Unit / section",
        type: "text",
        help: "For non-academic staff, e.g. ICT Unit, Bursary, University Bookshop.",
      },
      { name: "email", label: "Email", type: "text" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "linkedin", label: "LinkedIn profile", type: "text" },
      {
        name: "orcid",
        label: "ORCID",
        type: "text",
        help: "e.g. https://orcid.org/0000-0002-1825-0097",
      },
      { name: "googleScholar", label: "Google Scholar", type: "text" },
      { name: "scopus", label: "Scopus", type: "text" },
      { name: "researchGate", label: "ResearchGate", type: "text" },
      { name: "academia", label: "Academia.edu", type: "text" },
      { name: "webOfScience", label: "Web of Science / Publons", type: "text" },
      { name: "ssrn", label: "SSRN", type: "text" },
      { name: "biography", label: "Biography", type: "textarea", rows: 6 },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["active", "inactive"],
      },
    ],
  },

  documents: {
    title: "Documents & Reports",
    singular: "document",
    endpoint: "/api/documents",
    columns: [
      { key: "title", label: "Title" },
      { key: "category", label: "Category" },
      { key: "fileName", label: "File" },
      { key: "status", label: "Status" },
    ],
    defaults: { status: "active" },
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      {
        name: "file",
        label: "File",
        type: "file",
        required: true,
        help: "PDF, Word, Excel or PowerPoint — up to 20 MB.",
        // The uploader edits one value but the Document table stores four
        // columns, so map them here.
        targets: {
          url: "fileUrl",
          name: "fileName",
          size: "fileSize",
          type: "fileType",
        },
      },
      { name: "description", label: "Description", type: "textarea" },
      {
        name: "category",
        label: "Category",
        type: "text",
        help: "e.g. Annual report, Policy, Sustainability.",
      },
      {
        name: "status",
        label: "Visibility",
        type: "select",
        options: ["active", "hidden"],
      },
    ],
  },

  lectures: {
    title: "Inaugural Lectures",
    singular: "lecture",
    endpoint: "/api/lectures",
    columns: [
      { key: "number", label: "No." },
      { key: "lecturer", label: "Lecturer" },
      { key: "title", label: "Title" },
      { key: "lectureDate", label: "Date", format: "date" },
      { key: "status", label: "Status" },
    ],
    defaults: { status: "published", sortOrder: 0 },
    fields: [
      {
        name: "number",
        label: "Lecture number",
        type: "number",
        required: true,
        help: "e.g. 32 for the 32nd inaugural lecture — this is the number shown in the badge.",
      },
      { name: "lecturer", label: "Inaugural lecturer", type: "text" },
      {
        name: "lecturerRole",
        label: "Lecturer title / professorship",
        type: "text",
        help: "e.g. Professor of Immunology.",
      },
      { name: "title", label: "Lecture title", type: "text" },
      { name: "summary", label: "Summary", type: "textarea" },
      { name: "lectureDate", label: "Date delivered", type: "date" },
      { name: "venue", label: "Venue", type: "text" },
      {
        name: "file",
        label: "Proceedings / PDF",
        type: "file",
        help: "Optional PDF or document of the lecture — up to 20 MB.",
        targets: { url: "fileUrl" },
      },
      { name: "status", label: "Status", type: "select", options: STATUS_EDITORIAL },
      { name: "sortOrder", label: "Display order", type: "number" },
    ],
  },

  announcements: {
    title: "Announcements",
    singular: "announcement",
    endpoint: "/api/announcements",
    columns: [
      { key: "title", label: "Title" },
      { key: "priority", label: "Priority" },
      { key: "status", label: "Status" },
      { key: "publishedAt", label: "Published", format: "date" },
      { key: "expiresAt", label: "Expires", format: "date" },
    ],
    defaults: { status: "draft", priority: 1 },
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      {
        name: "content",
        label: "Message",
        type: "textarea",
        required: true,
        rows: 3,
      },
      {
        name: "priority",
        label: "Priority",
        type: "number",
        help: "Higher numbers appear first in the announcement bar.",
      },
      { name: "status", label: "Status", type: "select", options: STATUS_EDITORIAL },
      { name: "publishedAt", label: "Publish at", type: "date" },
      {
        name: "expiresAt",
        label: "Expires at",
        type: "date",
        help: "Leave blank to keep it visible indefinitely.",
      },
    ],
  },

  postgraduateProgrammes: {
    title: "Postgraduate Programmes",
    singular: "programme",
    endpoint: "/api/programmes",
    columns: [
      { key: "name", label: "Programme" },
      { key: "award", label: "Award" },
      { key: "faculty", label: "Faculty" },
      { key: "status", label: "Status" },
    ],
    defaults: { status: "published", sortOrder: 0 },
    fields: [
      {
        name: "name",
        label: "Programme name",
        type: "text",
        required: true,
        help: "e.g. M.Sc. Computer Science",
      },
      {
        name: "award",
        label: "Award",
        type: "select",
        required: true,
        options: [
          "PGD",
          "M.Sc.",
          "M.A.",
          "MBA",
          "MPA",
          "MIT",
          "M.Ed.",
          "DBA",
          "Ph.D.",
        ],
      },
      {
        name: "faculty",
        label: "Faculty",
        type: "text",
        required: true,
        help: "Programmes are grouped by this value on the public page.",
      },
      { name: "sortOrder", label: "Display order", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["published", "hidden"],
      },
    ],
  },

  messages: {
    title: "Enquiries",
    singular: "enquiry",
    endpoint: "/api/messages",
    // Enquiries arrive from the public forms — they are never typed in here.
    noCreate: true,
    columns: [
      { key: "name", label: "From" },
      { key: "email", label: "Email" },
      { key: "source", label: "Form" },
      { key: "status", label: "Status" },
      { key: "createdAt", label: "Received", format: "date" },
    ],
    defaults: { status: "new" },
    fields: [
      { name: "name", label: "From", type: "text", disabled: true },
      { name: "email", label: "Email", type: "text", disabled: true },
      { name: "phone", label: "Phone", type: "text" },
      { name: "programme", label: "Programme of interest", type: "text" },
      { name: "subject", label: "Subject", type: "text" },
      {
        name: "message",
        label: "Message",
        type: "textarea",
        rows: 8,
        disabled: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["new", "read", "replied", "archived"],
        help: "The sender's original wording is kept — only these fields are editable.",
      },
    ],
  },
};

export const ADMIN_NAV = [
  { path: "/admin", page: "dashboard", label: "Dashboard" },
  { path: "/admin/news", page: "news", label: "News" },
  { path: "/admin/events", page: "events", label: "Events" },
  { path: "/admin/announcements", page: "announcements", label: "Announcements" },
  { path: "/admin/messages", page: "messages", label: "Enquiries" },
  { path: "/admin/principal-officers", page: "principal-officers", label: "Principal Officers" },
  { path: "/admin/faculties", page: "faculties", label: "Faculties & Programmes" },
  { path: "/admin/departments", page: "departments", label: "Departments" },
  {
    path: "/admin/postgraduate-programmes",
    page: "postgraduate-programmes",
    label: "Postgraduate Programmes",
  },
  { path: "/admin/lectures", page: "lectures", label: "Inaugural Lectures" },
  { path: "/admin/gallery", page: "gallery", label: "Gallery" },
  { path: "/admin/staff", page: "staff", label: "Staff Directory" },
  { path: "/admin/documents", page: "documents", label: "Documents & Reports" },
  { path: "/admin/settings", page: "settings", label: "Site Settings" },
  { path: "/admin/users", page: "users", label: "Users & Roles", adminOnly: true },
];
